#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 30 13:46:08 2018

@author: brian
"""
import pandas as pd
from pandas_degreedays import yearly_month
from pandas_degreedays import calculate_dd


# Growing Degree Days
#from preprocessing.py load dfMasterMet (daily)

dfMasterMet.info()
dfMasterMet.columns
dfMasterMet['avgdailytemp'] = (dfMasterMet.tmmx + dfMasterMet.tmmn)/2

# pandas_degreedays
idx = dfMasterMet['daysabove_avg5.5'].index
s_idx = pd.Series(idx, index=idx)
diff_idx = s_idx-s_idx.shift(1)
s_sampling_period = diff_idx.value_counts()
sampling_period = s_sampling_period.index[0] # most prevalent sampling period
not_sampling_period = (diff_idx != sampling_period) # True / False


df_degreedays = calculate_dd(dfMasterMet['avgdailytemp'], method='pro', typ='heating')
#, Tref=5.5, group=lambda dt: yearly_month(dt, 1)
# geting errors.... maybe ill just sum avgdailytemp for each month and see if it is useful before 
#calculating proper GDDs



# write my own function... not even close. restart at year, hmm.. 
for row in df:
    if df['daysabove_avg5.5'] is True:
        df['GDD'] += (df['tmmx'] + df['tmmn'])/2



dfMasterMetMonthly = None
dfMasterMetMonthly = dfMasterMet.groupby('system:indexviejuno').resample('M')\
.agg({ 'daysbelowneg5':'sum',\
'tmmx':'mean', 'daysabove28':'sum', 'daysabove30':'sum', 'daysabove35':'sum',\
'cum_daysinarow_lowpr':'max', 'daysabove_avg5.5':'sum'})
    
dfMasterMetMonthly = None
dfMasterMetMonthly = dfMasterMet.groupby('system:indexviejuno').resample('M')\
.agg({ 'daysbelowneg5':'sum',\
 'daysabove_avg5.5':'sum', 'avgtemp':'sum'})