#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  2 14:12:44 2018

@author: brian
"""

import simplekml
#import numpy as np
import pandas as pd
#import seaborn as sns
#import matplotlib.pyplot as plt
#sns.set(style="whitegrid")

crop_id = 24
crop_id = str(crop_id)
data_path = '../rawData/AgMet/'

met = pd.read_csv(data_path + 'MeteorMonthly_roll_' + crop_id + ".csv")
ndvi = pd.read_csv(data_path + 'VegInd4_' + crop_id + ".csv")
    
# mess with data types in individual ararys, for a clean merge
met.date = pd.to_datetime(met.date).astype(str)
met.month = met.month.astype(int)
met.year = met.year.astype(int)
# Merge
dfMaster = None
dfMaster = met.merge(ndvi, on = ['pixel', 'date','year','month'])
## return df with only unique lat long combo
df = dfMaster[['Longitude','Latitude']].drop_duplicates()


kml = simplekml.Kml()
df.apply(lambda X: kml.newpoint(coords=[( X["Longitude"],X["Latitude"])]) ,axis=1)  #name=X["pixel"], 
kml.save(path = "../Processed/"+ crop_id +"pixel_data.kml")

